# Generated by Codex on 2026-03-05
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("irrigation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherObservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField()),
                ("temperature_c", models.FloatField(blank=True, null=True)),
                ("precipitation_mm", models.FloatField(blank=True, null=True)),
                ("humidity_percent", models.FloatField(blank=True, null=True)),
                (
                    "site",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="irrigation.site"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("site", "timestamp"), name="unique_site_timestamp")
                ]
            },
        ),
        migrations.CreateModel(
            name="WeatherImportLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(choices=[("SUCCESS", "Success"), ("FAILED", "Failed")], max_length=10)),
                ("error_message", models.TextField(blank=True)),
                (
                    "site",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="irrigation.site"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("site", "date"), name="unique_site_date")
                ]
            },
        ),
    ]
