# Generated by Django 4.2.29 on 2026-09-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherimportlog',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='retrieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
