# Generated by Codex on 2026-03-05
from __future__ import annotations

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models
import django.db.models.deletion

from apps.irrigation.models import default_modbus_port, default_modbus_unit_id


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("timezone", models.CharField(default=settings.TIME_ZONE, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="RelayDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("host", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField(default=default_modbus_port)),
                ("unit_id", models.PositiveIntegerField(default=default_modbus_unit_id)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "site",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="irrigation.site"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Valve",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(8)])),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active_high", models.BooleanField(default=True)),
                ("default_max_duration_seconds", models.PositiveIntegerField(default=1800)),
                ("last_known_is_open", models.BooleanField(default=False)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "relay_device",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="irrigation.relaydevice"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("relay_device", "channel"), name="unique_relay_channel")
                ]
            },
        ),
        migrations.CreateModel(
            name="ScheduleRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=True)),
                ("days_of_week_mask", models.PositiveIntegerField(default=0)),
                ("start_time", models.TimeField()),
                ("mode", models.CharField(choices=[("FIXED", "Fixed"), ("DYNAMIC", "Dynamic")], max_length=10)),
                ("fixed_duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("max_duration_seconds", models.PositiveIntegerField(validators=[MinValueValidator(60)])),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "valve",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="irrigation.valve"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IrrigationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("trigger", models.CharField(choices=[("SCHEDULED", "Scheduled"), ("MANUAL", "Manual"), ("FAILSAFE", "Failsafe"), ("RECOVERY", "Recovery")], max_length=10)),
                ("requested_start_at", models.DateTimeField(blank=True, null=True)),
                ("planned_start_at", models.DateTimeField(blank=True, null=True)),
                ("actual_start_at", models.DateTimeField(blank=True, null=True)),
                ("optimal_duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("max_duration_seconds", models.PositiveIntegerField()),
                ("actual_stop_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("PLANNED", "Planned"), ("RUNNING", "Running"), ("FINISHED", "Finished"), ("FAILED", "Failed")], max_length=10)),
                ("stop_reason", models.CharField(blank=True, choices=[("COMPLETED", "Completed"), ("MANUAL_STOP", "Manual stop"), ("FAILSAFE_TIMEOUT", "Failsafe timeout"), ("ERROR", "Error")], max_length=20, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "valve",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="irrigation.valve"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status"], name="irrigation__status_idx"),
                    models.Index(fields=["planned_start_at"], name="irrigation__planned_idx"),
                ]
            },
        ),
    ]
