# Generated by Django 4.2.29 on 2026-03-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0003_add_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
