# Generated by Django 4.2.29 on 2026-03-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0004_schedule_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_mm', models.FloatField(default=0.0)),
                ('max_mm', models.FloatField(default=7.0)),
                ('g', models.FloatField(default=0.1852)),
                ('m', models.FloatField(default=25.6653)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curve_settings', to='irrigation.site')),
            ],
        ),
    ]
