# Generated by Django 4.2.29 on 2026-09-21 10:16

import apps.irrigation.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def normalize_dynamic_rules(apps, schema_editor):
    apps.get_model('irrigation', 'ScheduleRule').objects.using(
        schema_editor.connection.alias
    ).filter(mode='DYNAMIC').update(mode='FIXED')


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0006_relay_flash_duration_limits'),
    ]

    operations = [
        migrations.RunPython(normalize_dynamic_rules, migrations.RunPython.noop),
        migrations.CreateModel(
            name='GroupedRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('FIXED', 'Fixed'), ('SMART', 'Smart')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('days_of_week_mask', models.PositiveIntegerField(default=127)),
                ('start_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupedRuleValve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('duration_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3276)])),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RuleOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('FIXED', 'Fixed'), ('SMART', 'Smart')], max_length=10)),
                ('config', models.JSONField(default=dict)),
                ('decision', models.JSONField(default=dict)),
                ('scheduled_local_date', models.DateField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField()),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('reservation_end', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('MANUAL', 'Manual')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('STOPPING', 'Stopping'), ('FINISHED', 'Finished'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('ZERO', 'Zero')], default='PENDING', max_length=10)),
                ('cancellation_requested', models.BooleanField(default=False)),
                ('outcome', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='curvesettings',
            name='coverage_days',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='curvesettings',
            name='fallback_temperature_c',
            field=models.FloatField(blank=True, null=True, validators=[apps.irrigation.models.validate_finite]),
        ),
        migrations.AddField(
            model_name='irrigationrun',
            name='application_rate_mm_h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationrun',
            name='attempt_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationrun',
            name='attempt_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationrun',
            name='cancellation_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irrigationrun',
            name='closure_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationrun',
            name='delivery_uncertain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='irrigationrun',
            name='member_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationrun',
            name='pass_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='admission_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='valve',
            name='application_rate_mm_h',
            field=models.FloatField(blank=True, null=True, validators=[apps.irrigation.models.validate_application_rate]),
        ),
        migrations.AlterField(
            model_name='curvesettings',
            name='g',
            field=models.FloatField(default=0.1852, validators=[apps.irrigation.models.validate_finite]),
        ),
        migrations.AlterField(
            model_name='curvesettings',
            name='m',
            field=models.FloatField(default=25.6653, validators=[apps.irrigation.models.validate_finite]),
        ),
        migrations.AlterField(
            model_name='curvesettings',
            name='max_mm',
            field=models.FloatField(default=7.0, validators=[apps.irrigation.models.validate_finite]),
        ),
        migrations.AlterField(
            model_name='curvesettings',
            name='min_mm',
            field=models.FloatField(default=0.0, validators=[apps.irrigation.models.validate_finite]),
        ),
        migrations.AlterField(
            model_name='schedulerule',
            name='mode',
            field=models.CharField(choices=[('FIXED', 'Fixed')], max_length=10),
        ),
        migrations.AddField(
            model_name='ruleoccurrence',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='irrigation.groupedrule'),
        ),
        migrations.AddField(
            model_name='ruleoccurrence',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrigation.site'),
        ),
        migrations.AddField(
            model_name='groupedrulevalve',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='irrigation.groupedrule'),
        ),
        migrations.AddField(
            model_name='groupedrulevalve',
            name='valve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrigation.valve'),
        ),
        migrations.AddField(
            model_name='groupedrule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouped_rules', to='irrigation.schedule'),
        ),
        migrations.AddField(
            model_name='irrigationrun',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='irrigation.ruleoccurrence'),
        ),
        migrations.AddConstraint(
            model_name='irrigationrun',
            constraint=models.UniqueConstraint(fields=('occurrence', 'valve', 'pass_number'), name='unique_occurrence_valve_pass'),
        ),
        migrations.AddIndex(
            model_name='ruleoccurrence',
            index=models.Index(fields=['site', 'status'], name='occurrence_site_status'),
        ),
        migrations.AddConstraint(
            model_name='ruleoccurrence',
            constraint=models.UniqueConstraint(fields=('rule', 'scheduled_local_date'), name='unique_rule_local_date'),
        ),
        migrations.AddConstraint(
            model_name='groupedrulevalve',
            constraint=models.UniqueConstraint(fields=('rule', 'valve'), name='unique_group_valve'),
        ),
        migrations.AddConstraint(
            model_name='groupedrulevalve',
            constraint=models.UniqueConstraint(fields=('rule', 'order'), name='unique_group_order'),
        ),
    ]
