# Generated by Django 4.2.29 on 2026-09-21 11:54

from django.db import migrations


def supply_fallback_defaults(apps, schema_editor):
    alias = schema_editor.connection.alias
    curve_settings = apps.get_model('irrigation', 'CurveSettings')
    sites = apps.get_model('irrigation', 'Site')
    curve_settings.objects.using(alias).filter(
        fallback_temperature_c__isnull=True
    ).update(fallback_temperature_c=25.0)
    missing_site_ids = sites.objects.using(alias).filter(
        curve_settings__isnull=True
    ).values_list('pk', flat=True)
    curve_settings.objects.using(alias).bulk_create([
        curve_settings(site_id=site_id, fallback_temperature_c=25.0)
        for site_id in missing_site_ids
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0007_groupedrule_groupedrulevalve_ruleoccurrence_and_more'),
    ]

    operations = [
        migrations.RunPython(supply_fallback_defaults, migrations.RunPython.noop),
    ]
