# Generated by Django 4.2.29 on 2026-09-21 11:57

import apps.irrigation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    # Commit the preceding backfill's deferred foreign-key checks before this
    # schema change; PostgreSQL cannot ALTER a table with pending trigger events.
    dependencies = [
        ('irrigation', '0008_fallback_temperature_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curvesettings',
            name='fallback_temperature_c',
            field=models.FloatField(default=25.0, validators=[apps.irrigation.models.validate_finite]),
        ),
    ]
