# Generated by Django 4.2.29 on 2026-09-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0009_require_fallback_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationrun',
            name='sender_interrupted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='irrigationrun',
            name='dispatch_state',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('UNSENT', 'Awaiting sender'), ('SENDING', 'Opening in flight'), ('DONE', 'Sender acknowledged')], default='LEGACY', editable=False, max_length=8),
        ),
    ]
