# Generated by Django 4.2.29 on 2026-09-21 21:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0010_irrigationrun_dispatch_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationrun',
            name='dispatch_state',
            field=models.CharField(choices=[('LEGACY', 'Legacy'), ('UNSENT', 'Legacy unsent'), ('SENDING', 'Legacy sender in flight'), ('QUEUED', 'Queued'), ('OPENING', 'Controller opening'), ('DONE', 'Dispatch complete')], default='DONE', editable=False, max_length=8),
        ),
        migrations.CreateModel(
            name='ValveClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('valve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure_request', to='irrigation.valve')),
            ],
        ),
    ]
